[package]
name = "debridge_anchor_extensions_macro"
version.workspace = true
authors.workspace = true
edition.workspace = true


[lib]
proc-macro = true

[dependencies]
anchor-syn = "0"
heck = "0.4.1"

syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
